<?php

namespace Autolina\BlacklistBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends EntityRepository
{
	public function findOnebyOne()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT e FROM AutolinaBlacklistBundle:Blacklist e ORDER BY e.id ASC'
			)
			->getResult();
	}
}
