<?php

namespace Autolina\newBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Black_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Black_listRepository extends EntityRepository
{
	public function findOnebyOne()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT e FROM AutolinanewBundle:Black_list e ORDER BY e.id ASC'
			)
			->getResult();
	}
}
