<?php

namespace Autolina\SampleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends EntityRepository
{
	public function findOnebyOne()
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT e FROM AutolinaSampleBundle:Mail e ORDER BY e.id ASC'
			)
			->getResult();
	}
}
